### ISSUE TITLE
source profile check

### ISSUE THREAD

**Issue by limnoliver** [limnoliver/pah_glri#4]
I was trying to figure out how to adjust for keeping or excluding creosote since the source profile table was provided with calculated proportions for the 12-compound list. In doing so, I noticed that almost all of the sources sum nicely to 1, except for "UMO1" which sums to 1.078. @akbaldwi-usgs do you know what's going on here?

**Comment by akbaldwi-usgs** [comment]
Good catch, Sam. I looked back at the Van Metre and Mahler 2014 report,
which is where that profile came from, and their numbers are the same
(summing to 1.08). I'm wondering if this is a rounding issue or what. I'll
dig in a little more, will keep you in the loop.

Austin

*Austin Baldwin | *USGS Idaho Water Science Center | 230 Collins Rd, Boise,
ID  83702 |
office:(208) 387-1365  cell:(208) 912-9021 | akbaldwi@usgs.gov

**Comment by limnoliver** [comment]
Saw Pete's response - will adjust! Thanks for sorting out.

**Comment by limnoliver** [comment]
@akbaldwi-usgs this was fixed in the PAH package where I re-standardized the profiles so UMO1 now sums to 1. Reinstall the package and remake pah_glri to get updated results.
